[project]
name = "prompt-engineering"
version = "0.0.0"
requires-python = ">=3.12"
dependencies = [
    "dotenv",
    "bs4",
    "pandas",
    "openpyxl>=3.1.5",
]

[dependency-groups]
google = [
    "google-generativeai"
]
huggingface = [
    "transformers",
]
